# cloudbuild.yaml

steps:
# 0. Build Backend Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/playlist-tracker-backend:latest', './backend']
  dir: '.'

# 1. Explicitly Push Backend Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/playlist-tracker-backend:latest']
  id: Push Backend Image

# 2. Deploy Backend to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - run
  - deploy
  - playlist-tracker-backend # Name of your backend Cloud Run service
  - --image=gcr.io/${PROJECT_ID}/playlist-tracker-backend:latest
  - --region=europe-west1 # Ensure your consistent region
  - --platform=managed
  - --allow-unauthenticated
  - --port=5000
  - --set-env-vars=DB_URI=${_DB_URI},JWT_SECRET=${_JWT_SECRET},YOUTUBE_API_KEY=${_YOUTUBE_API_KEY}
  - --timeout=300
  - --cpu=1
  - --memory=512Mi
  - --max-instances=2
  - --min-instances=0
  - --project=${PROJECT_ID}
  id: Deploy Backend Service

# 3. Get the URL of the deployed Backend Service
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Get Backend URL
  env:
    - 'PROJECT_ID=${PROJECT_ID}'
  script: |
    gcloud run services describe playlist-tracker-backend \
      --platform=managed \
      --region=europe-west1 \
      --format='value(status.url)' \
      --project=$PROJECT_ID > /workspace/backend_url.txt

# 4. Build Frontend Docker Image
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      BACKEND_URL=$(cat /workspace/backend_url.txt)
      docker build \
        -t gcr.io/${PROJECT_ID}/playlist-tracker-frontend:latest \
        --build-arg REACT_APP_BACKEND_URL="$BACKEND_URL" \
        ./frontend
  dir: '.'

# 5. Explicitly Push Frontend Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/playlist-tracker-frontend:latest']
  id: Push Frontend Image

# 6. Deploy Frontend to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - run
  - deploy
  - playlist-tracker-frontend
  - --image=gcr.io/${PROJECT_ID}/playlist-tracker-frontend:latest
  - --region=europe-west1
  - --platform=managed
  - --allow-unauthenticated
  - --port=80
  - --timeout=900
  - --cpu=1
  - --memory=256Mi
  - --max-instances=2
  - --min-instances=0
  - --project=${PROJECT_ID}
  id: Deploy Frontend Service

substitutions:
  _DB_URI: ""
  _JWT_SECRET: ""
  _YOUTUBE_API_KEY: ""

options:
  logging: CLOUD_LOGGING_ONLY