# cloudbuild.yaml

steps:
# 0. Build Backend Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/playlist-tracker-backend:latest', './backend']
  dir: '.' # Execute from the project root

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/playlist-tracker-backend:latest']
  id: Push Backend Image # Give this step an ID for clarity

# 1. Deploy Backend to Cloud Run (This step's index will now be 2)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - run
  - deploy
  - playlist-tracker-backend # Name of your backend Cloud Run service
  - --image=gcr.io/${PROJECT_ID}/playlist-tracker-backend:latest
  - --region=europe-west1 # Ensure your consistent region
  - --platform=managed
  - --allow-unauthenticated
  - --port=5000
  - --set-env-vars=DB_URI=${_DB_URI},JWT_SECRET=${_JWT_SECRET},YOUTUBE_API_KEY=${_YOUTUBE_API_KEY}
  - --timeout=900
  - --cpu=1
  - --memory=512Mi
  - --max-instances=2
  - --min-instances=0
  - --project=${PROJECT_ID}
  id: Deploy Backend Service

# 2. Get the URL of the deployed Backend Service
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Get Backend URL
  env:
    - 'PROJECT_ID=${PROJECT_ID}'
  script: |
    gcloud run services describe playlist-tracker-backend \
      --platform=managed \
      --region=europe-west1 \
      --format='value(status.url)' \
      --project=$PROJECT_ID > /workspace/backend_url.txt


# 3. Build Frontend Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/playlist-tracker-frontend:latest', './frontend']
  dir: '.'

# 4. Deploy Frontend to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - run
  - deploy
  - playlist-tracker-frontend
  - --image=gcr.io/${PROJECT_ID}/playlist-tracker-frontend:latest
  - --region=europe-west1
  - --platform=managed
  - --allow-unauthenticated
  - --port=80
  - --set-env-vars=REACT_APP_API_URL=$(cat /workspace/backend_url.txt)
  - --timeout=900
  - --cpu=1
  - --memory=256Mi
  - --max-instances=2
  - --min-instances=0
  - --project=${PROJECT_ID}
  id: Deploy Frontend Service

substitutions:
  _DB_URI: ""
  _JWT_SECRET: ""
  _YOUTUBE_API_KEY: ""

options:
  logging: CLOUD_LOGGING_ONLY